name = "Witchcraft"
author = "restedwicked.xyz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074726cf7004cf1ecdec952a6b60272f0639c58e6c58eda509e4df6950c4339c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.180"
