name = "Witchcraft"
author = "restedwicked.xyz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "909deb6f0a806f1f406257492da33a79e6121d311f20e871a3dd21a470b958c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.180"
