name = "Witchcraft"
author = "restedwicked.xyz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e56c61505b97ee493fa5574c277164273741dc0a96b959fabd8bee0fc831a13e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.180"
